### PR TITLE
fix issue about twice next call

### PR DESCRIPTION
**Pull request by lcalvy**
fix issue #1
Next handling could be more granular, map call only next  if nothing to
do or if no success handler is configured
If success handler is configured, next must be only call on this one

### CODE REVIEW

**Comment by plouc** [comment]
@lcalvy, this PR breaks tests for older nodejs version

**Comment by lcalvy** [comment]
about 0.8 npm syntax is reponsible.
about 0.4 nvm is craching.
`The command "nvm install 0.4" failed and exited with 2 during .` 
I think it could be remove

**Comment by plouc** [comment]
yes, we can remove the 0.4, could you update the travis file please ?

**Comment by plouc** [comment]
You should also update the doc as it reference the usage of the now deprecated debug option.

**Comment by lcalvy** [comment]
i think a could leave debug method and throw a warning to avoid breaking

**Comment by lcalvy** [comment]
+1 @plouc could you also npm publish?

**Comment by plouc** [comment]
@lcalvy done

**Pull request merged**
